### ISSUE TITLE
Selling items to some merchants is broken

### ISSUE THREAD

**Issue by elliotkendall** [nuvie/nuvie#54] opened 2016-02-14 07:14 UTC
Arms/armor seems to be working correctly, but some of the other merchants don't seem to be able to tell that I have items ready to sell them. For example, I can't sell thread to Thindle or cloth to Marissa in Paws.

**Comment by malignantmanor** [comment] 2016-02-16 21:01
I can confirm the issue. Here is an original saved game and a Nuvie one. Thindle is in the same room. Marissa is in the building across the street.

[can't sell thread.zip](https://github.com/nuvie/nuvie/files/133291/can.t.sell.thread.zip)

**Comment by Zabeus** [comment] 2017-10-15 23:19
Obj::get_total_qty() is returning 0 for objects in inventory.

**Comment by malignantmanor** [comment] 2017-11-13 23:49
I think you were right in your comment when you were questioning get_total_qty returning 0. Fixing get_total_qty is probably the better solution. How does the following patch look to you?
[Fix-issue-54.zip](https://github.com/nuvie/nuvie/files/1469054/Fix-issue-54.zip)

**Comment by malignantmanor** [comment] 2017-12-23 19:28
I went ahead and applied my version of the fix due to someone else reporting this issue. It should be fixed with commit 96275a472de73a93c0d70e57cfb2b1949de0761e

**Closed by malignantmanor** 2017-12-23 19:28 UTC
