### ISSUE TITLE
OS X: original+ is not getting any input

### ISSUE THREAD

**Issue by HiPhish** [nuvie/nuvie#47] opened 2015-12-27 13:48 UTC
As the title implies, when the game is in original+ style input is not registered, neither mouse nor keyboard, neither fullscreen nor windowed. Original and new style work fine. Tested the rev 1927 build on OS X 10.11.2.

**Comment by DominusExult** [comment] 2016-01-05 08:43
I can confirm this. This time it's seemingly not an SDL2-port issue since it misbehaves in both SDL 1.x and SDL2 builds ;(

**Comment by yuv422** [comment] 2016-08-26 13:10
This should be fixed now. :)

**Closed by yuv422** 2016-08-26 13:10 UTC
