### ISSUE TITLE
OS X: data directory not found

### ISSUE THREAD

**Issue by HiPhish** [nuvie/nuvie#45] opened 2015-12-25 12:48 UTC
I downloaded the latest OS X build (rev 1927) and I get the error
```
Error: cannot open datadir!
```
on start. This did not happen in the 0.5 release. The binary cannot find the directory because it is searching in its current path. `cd`ing into the `Resources` directory of the app bundle and then launching the nuvie binary via `../MacOS/nuvie` solves the problem.

**Comment by DominusExult** [comment] 2015-12-25 13:04
Ok, that's odd. I'll see if I can reproduce and find the cause. No new snapshot will be available until after some days after new years.
What version of OS X are you using?

**Comment by HiPhish** [comment] 2015-12-25 13:06
I'm using 10.11.2 and as I said it is working in the old release. I ran a `diff` on both Info.plist files, they are identical, so the issue has to be in the binary itself. You don't have to hurry with it, I just wanted to let you know of the issue.

**Comment by DominusExult** [comment] 2015-12-25 13:43
The difference is that between the builds the SDL2 fork became the default and something in that fork must have screwed up. Curios because I was sure I at least started the build without problems (but that might have picked up the data elsewhere on my build system).

**Comment by DominusExult** [comment] 2015-12-27 13:41
So, tested on a clean non-developer machine and indeed something is screwy.
Can't check the code but perhaps an ifdef changed so that the bundle is no longer checked first before checking the data folder specified in the Nuvie Preference file.
The defaults for the other games also look a bit off in the preference file (a < too many and same paths for all the keyfile override).
Eric, maybe you can take a look? I'm still at least a week away from code ;)

**Comment by yuv422** [comment] 2015-12-28 21:22
Yeah it looks like I mistakenly removed the bundle checking code from the SDL2 compile. :(

SDL2 doesn't need "-Wl,-framework,Cocoa" so the compile was failing. I just assumed it wasn't needed with SDL2

**Comment by yuv422** [comment] 2016-01-04 10:02
This should be fixed in the latest daily build

**Closed** 2016-01-04 10:02 UTC
